### ISSUE TITLE
Invalid code point

### ISSUE THREAD

**Issue by sjlu** [mdevils/html-entities#48]
When decoding the following string: `In today&#2013266066;s digital marketplace`

It results in this error:
```
RangeError: Invalid code point 2013266066
  at Object.fromCodePoint (<anonymous>)
  at /Users/sjlu/Code/interseller/node_modules/html-entities/lib/html5-entities.js:27:49
  at String.replace (<anonymous>)
  at Html5Entities.decode (/Users/sjlu/Code/interseller/node_modules/html-entities/lib/html5-entities.js:16:20)
```

```
node --version
v12.18.3
```

**Comment by sjlu** [comment]
The previous error was from `1.4.0`. `2.0.2` produces a similar error:

```
RangeError: Invalid code point 2013266066
     at Object.fromCodePoint (<anonymous>)
     at /Users/sjlu/Code/interseller/node_modules/html-entities/lib/index.js:1:2512
     at String.replace (<anonymous>)
     at a.decode (/Users/sjlu/Code/interseller/node_modules/html-entities/lib/index.js:1:2332)
```

**Comment by mdevils** [comment]
Hello @sjlu, is it actually a valid html entity / unicode character?

**Comment by sjlu** [comment]
@mdevils I don't think so, but should `decode` leave it be and skip the character in the string rather than failing with an error?

**Comment by mdevils** [comment]
@sjlu good point.

**Comment by mdevils** [comment]
Fixed in `2.0.3`

**Comment by sjlu** [comment]
Awesome, thanks @mdevils

**Comment by mdevils** [comment]
The fix was modified to mimic browser behaviour.
